src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cette email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column(type: 'string', length: 200, nullable: true)]
    private ?string $resetToken;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getRoles(): array
    {
        // Si vous avez ajusté votre entité pour stocker les rôles comme un tableau sans JSON
        $roles = $this->roles;
        // garantir que chaque utilisateur a au moins le rôle ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }
    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\User1Type;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/user')]
#[IsGranted('ROLE_ADMIN')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new (Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Hash le mot de passe avant de persister l'utilisateur
            $user->setPassword(
                $passwordHasher->hashPassword(
                    $user,
                    $user->getPassword()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Hash le mot de passe uniquement si le champ mot de passe a été modifié
            // Cela suppose que votre formulaire a un champ pour le mot de passe
            // Vous pouvez vérifier cela selon la logique de votre application
            if ($form->get('password')->isSubmitted()) {
                $user->setPassword(
                    $passwordHasher->hashPassword(
                        $user,
                        $form->get('password')->getData()
                    )
                );
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete'~user.id) }}">
    <button class="btn my-3 btn-danger form-control btn-lg">Delete</button>
</form>

templates/user/_form.html.twig
{# user/_form.html.twig #}

{{ form_start(form) }}

{% for choice in form.roles %}
    <div class="form-group">
        <div class="form-check">
            {{ form_widget(choice, {'attr': {'class': 'form-check-input'}}) }}
            {{ form_label(choice, choice.vars.label, {'label_attr': {'class': 'form-check-label'}}) }}
        </div>
    </div>
{% endfor %}

<div class="form-group">
    {{ form_label(form.email) }}
    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    <div class="form-check form-switch">
        {{ form_widget(form.is_verified, {
            'id': 'isVerifiedSwitch', 
            'attr': {
                'class': 'form-check-input',
                'role': 'switch',
                'disabled': true  
            }
        }) }}
        {{ form_label(form.is_verified, 'Vérifié', { 
            'label_attr': {'class': 'form-check-label', 'for': 'isVerifiedSwitch'}
        }) }}
    </div>
</div>


<div class="form-group">
    {{ form_label(form.password) }}
    {{ form_widget(form.password, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.resetToken) }}
    {{ form_widget(form.resetToken, {'attr': {'class': 'form-control'}}) }}
</div>

<button class="btn btn-success btn-lg" >{{ button_label|default('Save') }}</button>
<a href="{{ path('app_user_index') }}" class="btn btn-secondary btn-lg">Retourner dashbord user</a>


{{ form_end(form) }}

templates/user/edit.html.twig
{% block stylesheets %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="{{ asset('styles/user/user-edit.css') }}">
{% endblock %}

{% block body %}
	{% include "admin/partial/_navBarAdmin.html.twig" %}
	<div class="edit-user-container mb-5">
		<h1>Edit User</h1>


		{{ include('user/_form.html.twig', {'button_label': 'save'}) }}
		
	{{ include('user/_delete_form.html.twig') }}

		
	</div>
{% endblock %}

templates/user/index.html.twig
{% block stylesheets %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
{% endblock %}
{% block body %}
	{% include "admin/partial/_navBarAdmin.html.twig" %}
	<div class="container mt-5">
		<h1 class="mb-4">Utilisateur</h1>

		<div class="table-responsive">
			<table class="table table-hover">
				<thead class="table-dark">
					<tr>
						<th>Id</th>
						<th>Email</th>
						<th>Roles</th>
						<th>Is Verified</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for user in users %}
						<tr>
							<td>{{ user.id }}</td>
							<td>{{ user.email }}</td>
							<td>{{ user.roles|join(', ')|replace({'ROLE_': ''}) }}</td>

							<td>
								{% if user.isVerified %}
									<span class="badge bg-success">Oui</span>
								{% else %}
									<span class="badge bg-danger">Non</span>
								{% endif %}
							</td>
							<td>
								<a href="{{ path('app_user_show', {'id': user.id}) }}" class="btn btn-sm btn-info">Show</a>
								<a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-sm btn-primary">Edit</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="7">No records found</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<a href="{{ path('app_user_new') }}" class="btn btn-success">Create New</a>
	</div>




{% endblock %}

templates/user/new.html.twig
{% block stylesheets %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="{{ asset('styles/user/user-edit.css') }}">
{% endblock %}

{% block body %}
	{% include "admin/partial/_navBarAdmin.html.twig" %}
	<div class="edit-user-container mb-5">
    <h1>Créer un utilisateur</h1>

    {{ include('user/_form.html.twig') }}
</div>
{% endblock %}

templates/user/show.html.twig
{% block stylesheets %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href={{ asset('styles/user/user.css') }}>
{% endblock %}
{% block body %}
	{% include "admin/partial/_navBarAdmin.html.twig" %}
	<div class="user-details-container">
		<h1>User Details</h1>
		<table class="table">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ user.id }}</td>
				</tr>
				<tr>
					<th>Email</th>
					<td>{{ user.email }}</td>
				</tr>
				<tr>
					<th>Roles</th>
					<td>{{ user.roles|join(', ')|replace({'ROLE_': ''}) }}</td>

				</tr>
				<tr>
					<th>Is Verified</th>
					<td>
						<div class="form-check form-switch">
							<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheck{{ user.id }}" {{ user.isVerified ? 'checked' : '' }} disabled>
							<label class="form-check-label" for="flexSwitchCheck{{ user.id }}">{{ user.isVerified ? 'Verified' : 'Not Verified' }}</label>
						</div>
					</td>

				</tr>
			</tbody>
		</table>
		<a href="{{ path('app_user_index') }}" class="btn btn-secondary">Back to List</a>
		<a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-primary">Edit</a>
		{{ include('user/_delete_form.html.twig') }}
	</div>
{% endblock %}